### ISSUE TITLE
Storyboards: module name for target may not match "customModule" set by Xcode

### ISSUE THREAD

**Issue by djbe** [SwiftGen/templates#25]
If a project has 2 targets A and B, and a storyboard file is in both, whenever a scene's custom class is set in Xcode's UI, the `customModule` will also be (automatically) set to the current target's name in the storyboard's XML.

SwiftGen (by default) will preprend the module's name if there is one in the storyboard's XML, so this realisation above means that it will prepend the module name to any custom class, which does not allow generated files to be included by both targets A and B.

**Comment by AliSoftware** [comment]
@juli1quere care to add some more information about this issue you encountered, or even a sample project to reproduce? Thanks.

**Comment by jlnquere** [comment]
OK, this issue is a little bit strange. I wanted to build a demo project ... But everything is working as expected (i.e. SwiftGen do not add the module name). 

So, I dug into my original project. When I check with interface builder, my scenes are not set up with a custom module. But when I open it as an XML file, `customModule` is set ... 

![screen shot 2017-02-20 at 14 01 20](https://cloud.githubusercontent.com/assets/231661/23126119/9c15b35e-f775-11e6-8dc8-7467f940e5bd.png)


```
<viewController id="8d1-8q-ASZ" customClass="MainViewController" customModule="Kwote" customModuleProvider="target" sceneMemberID="viewController">
```

After removing all these ` customModule="Kwote"` manualy, everything works as expected. To sum up: this is clearly an Interface Builder issue, SwiftGen works as expected.

**Comment by AliSoftware** [comment]
Should we close this then? Or is it worth making a note somewhere to document this Interface Builder issue?

**Comment by jlnquere** [comment]
So @djbe: the solution for you would be to check that your scenes are not bound to a specific module. And you'll have to check in Interface Builder AND with XML editor :/

Edit: @AliSoftware just told me that you're not facing this issue ... Anyway :)

**Comment by djbe** [comment]
@juli1quere I think this is the behaviour Interface Builder is meant to have. Even if it's not, that doesn't mean we can can't do anything about it.

We could modify the following line:
```{% macro className scene %}{% if scene.customClass %}{% if scene.customModule %}{{scene.customModule}}.{% endif %}{{scene.customClass}}{% else %}UI{{scene.baseType}}{% endif %}{% endmacro %}```
To add a test around the `customModule` bit:
```{% macro className scene %}{% if scene.customClass %}{% if scene.customModule %}{% if not param.ignoreTargetModule or scene.customModule != env.PRODUCT_MODULE_NAME and scene != param.module %}{{scene.customModule}}.{% endif %}{% endif %}{{scene.customClass}}{% else %}UI{{scene.baseType}}{% endif %}{% endmacro %}```

Essentialy, you could add a cli parameter `--param ignoreTargetModule`, to disable prefixing custom classes with the target module. And if you're compiling this with multiple targets, add `--param module=Kwote` to always match the module in the storyboard.

**Comment by djbe** [comment]
By the way, you could test this right now using a custom template. With SwiftGen 4.2, you can pass along any custom parameters to the template.

**Comment by jlnquere** [comment]
Indeed, that could be a good option ! 

In fact, I think this IB issue is not transitory. I manually fixed my storyboard. Few days after, I updated it (just changed the content mode of an `UIImageView`). And, when I look my changelog, IB put back  `customModule="Kwote"` on every scene. Damned ! For example: 

```
-                <viewController id="8d1-8q-ASZ" customClass="MainViewController"  customModuleProvider="target" sceneMemberID="viewController">
+                <viewController id="8d1-8q-ASZ" customClass="MainViewController" customModule="Kwote" customModuleProvider="target" sceneMemberID="viewController">
``` 

I'll try the solution you suggest quickly.

**Comment by jlnquere** [comment]
So @djbe: I tried your workaround, it works perfectly. Thank you !

Now, I will try to understand why IB continue to add the `customModule` field.

**Comment by djbe** [comment]
I honestly think they just made it the default behaviour to avoid some class name ambiguity?
I'm glad the trick worked, we'll have to add it to the documentation when we get to it.

Ref #2.

**Comment by jlnquere** [comment]
Do you want me to make a PR with your workaround ?

**Comment by djbe** [comment]
Err sorry, getting some issues/PRs confused. Yes, a PR would be welcome!

**Comment by ldiqual** [comment]
@juli1quere Any update on this?

**Comment by jlnquere** [comment]
Hey ! I'm sorry, I did not seen the notifications on this. 

PR incoming 👨‍🚀
