### ISSUE TITLE
Suggestion for improvement of Strings template: `L13y`.

### ISSUE THREAD

**Issue by Sajjon** [SwiftGen/templates#60]
Dot-Syntax (DS) introduced a natural grouping of strings, like:
```swift
enum L10n {
    enum Screen {
        enum Profile {
            static let title = tr("Screen.Profile.Title")
            enum Label {
                static let firstName = tr("Screen.Profile.Label.FirstName")
                static let lastName = tr("Screen.Profile.Label.LastName")
                static let email = tr("Screen.Profile.Label.Email")
            }
        }
    }
}
```

It looks like the new template [structured-swift3](https://github.com/SwiftGen/templates/blob/master/templates/strings/structured-swift3.stencil) keeps this structure as well, right? I will still refer to this structured layout as Dot-Syntax (DS).

With DS we do not need to use the `.strings` property to get the `String` value from the `L10n` enum.

This allows us to write
```swift
override func viewDidLoad() {
    super.viewDidLoad()
    title = L10n.Screen.Profile.title
}
```
Instead of Non Dot-Syntax (NDS) version:
```swift
override func viewDidLoad() {
    super.viewDidLoad()
    title = L10n.screenProfileTitle.string
}
```

What's neat about DS is that it structures - groups - my strings together. More specifically DS groups my strings together into a *context* . All the strings relating the the *Profile screen*, shown in e.g. a ViewController `ProfileViewController`, are store within the nested enum `L10n.Screen.Profile.Label`.

One way of reasoning about DS structure is to look at it as a graph. More specifically a `tree`. Where `L10n` is the _root of the tree_ and where the localizable strings `static let myString: String` are _leaves_. And all nested types (enums) are nodes in the tree, being neither the root nor a leaf.

If our leaves are static string constants, let us call the nested type containing them *leaf type*. So given the `L10n` above, `enum L10n` is the **root**, `static let firstName: String` is a **leaf** and  (the nested type) `enum Label` is a **leaf type**.

The problem I see with the structure of the current DS is that I cannot pass a long a **leaf type** and later refer to one if its leaves. What I want is this:

```swift
func printProfileLabel(_ label: L10n.Screen.Profile.Label) {
    print(label) // huh? What to do?
}

printProfileLabel(.firstName) // Compilation error: "Member 'firstName' in 'L10n.Screen.Profile.Label' produces result of type 'String', but context expects 'L10n.Sceen.Profile.Label'"
```

This is an extremely simplified version of the scenario where I in my `ProfileViewController` would like to populate labels and not have to use the verbose syntax: `L10n.Sceen.Profile.Label.FirstName`. What I want to do, but not possible (?):

Given a subview called `LabelsView` holding two `UILabels`, one with compile time defined value "Firstname:" and other with content, run time based value "Alex" (my name) based on the Profile that we fetched from our Backend. Which is a very common scenario.

```swift
final class LabelsView: UIView {
    let titleLabel: UILabel
    let valueLabel: UILabel
    let stackView: UIStackView
    init(title: String, value: String) {
        titleLabel = UILabel(title)
        valueLabel = UILabel(value)
        //then stack them using UIStackView
        super.init(frame: .zero)
    }
}
```

```swift
// I want this...
class ProfileViewController: UIViewController {
    let user: User
    lazy var firstNameLabels: LabelsView = LabelsView(.firstName, value: self.user.firstName)
    lazy var lastNameLabels: LabelsView = LabelsView(.lastName, value: self.user.lastName)
    ....
}
```
Instead, using DS, we have to write like this:

```swift
// But DS can only offer this:
class ProfileViewController: UIViewController {
    let user: User
    lazy var firstNameLabels: LabelsView = LabelsView(L10n.Sceen.Profile.Label.firstName, value: self.user.firstName)
    lazy var lastNameLabels: LabelsView = LabelsView(L10n.Sceen.Profile.Label.lastName, value: self.user.lastName)
    ....
}
```
The shorter syntax I'm seeking would be possible using this version of `L10n`, lets call it `LocalizationKey` or `L13y` in short:

```swift

protocol Localizable: CustomStringConvertible {
    var translated: String { get }
}

extension Localizable {
    var description: String { return translated }
}

//MARK: - L13y, short for LocalizationKey
enum L13y: Localizable {
    indirect case screen(Screen)
    enum Screen: Localizable {
        
        indirect case profile(Profile)
        enum Profile: Localizable {
            case title
            
            indirect case label(Label)
            enum Label: Localizable {
                case firstName
                case lastName
                case email
                
                var translated: String {
                    switch self {
                    case .firstName:
                        return tr("Screen.Profile.Label.FirstName")
                    case .lastName:
                        return tr("Screen.Profile.Label.LastName")
                    case .email:
                        return tr("Screen.Profile.Label.Email")
                    }
                }
            }
            
            var translated: String {
                switch self {
                case .title:
                    return tr("Screen.Profile.Title")
                case .label(let label):
                    return label.translated
                }
            }
        }
        
        var translated: String {
            switch self {
            case .profile(let profile):
                return profile.translated
            }
        }
    }
    
    var translated: String {
        switch self {
        case .screen(let screen):
            return screen.translated
        }
    }
}

```

The `L13y` offers the same advantages as DS `L10n`, since it is indeed grouping the strings together. But since the leaves, e,g. `firstName` is not a static string, but rather an enum case - as in older Non Dot Syntax (NSD) version of `L10n` - we can pass it as a key.

```swift
extension LabelsView {
    // we can now pass the "leaf type" `L13y.Screen.Profile.Label`
    convenience init(_ key: L13y.Screen.Profile.Label, value: String) {
        self.init(key.translated, value: value)
    }
}

```
Which makes this short syntax possible:
```swift
// using convenience init above
lazy var firstNameLabels: LabelsView = LabelsView(.firstName, value: self.user.firstName)
```

Instead of this **verbose** syntax:
```swift
lazy var firstNameLabels: LabelsView = LabelsView(L10n.Sceen.Profile.Label.firstName, value: self.user.firstName)
```

The only disadvantage of using my proposed `L13y` is that we cannot directly refer to the string, but have to suffix the case with `.translated` to get a `String`.

```swift
 override func viewDidLoad() {
    super.viewDidLoad()
    title = L13y.Screen.Profile.title.translated //have to use `.translated`
}
```
Instead of Dot-Syntax version:

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    title = L10n.Screen.Profile.title
}
```

This can of course be mitigated using some postfix operator, e.g. caret `^` or dollar sign `$`

```swift
enum L13y: Localizable {...} // all nested types conforming to: `Localizable`
postfix operator ^
postfix func ^(localizable: Localizable) -> String { return key.translated }
```

so that:
```swift
title = L13y.Screen.Profile.title.translated
```
becomes:
```swift
title = L13y.Screen.Profile.title^
```

So the question really boiles down to:

## Do we in most cases refer to localizable strings within a specific context (e.g. ProfileViewController) or not?

And I think the answer to that question is **yes, we are working with localizable strings within a specific context most times**.

What are your thoughts?

One idea is of course to create a template creating both the `L10n` **and** the `L13y` enum?

#### Are there any other advantages with DS L10n over L13y I am missing?

**Comment by Sajjon** [comment]
@djbe Any input? :)

**Comment by djbe** [comment]
I'm currently swamped with work (and was away to a festival this weekend). I'll try to get back to this later this week or weekend.

**Comment by Sajjon** [comment]
@djbe Would really love to get some feedback here David 🙂

**Comment by djbe** [comment]
Hey man, apologies for the delay.

Your suggestion looks interesting. It could be greatly simplified by making the enums with string rawvalues (for the keys). That way, the `Localizable` string method could just do something like `NSLocalizedString(self.rawValue, ...`.

I don't know how this would integrate with the current structure, as we've decided that the main templates should only create enums with cases if the user could ever enumerate over the cases/rawvalues. Usually this isn't the case, and that's why we've adapted most of the templates.

We could consider adding this as an alternative template, but I'm wary of adding templates that only a small user group might use, that we'd then have to maintain like the other templates. @AliSoftware what do you think?

**Comment by Sajjon** [comment]
@djbe Hey! How would we let the enums conform to RawRepresentable (String)? Because take a look at this simple code

```swift
enum L10n: String {
    case yes, no
    case profile(Profile)
    enum Profile: String {
        case title = "Profile"
    }
}
```
This does not compile in Swift 3 (nor 4 probably), we get compilation error: 
```swift
error: enum with raw type cannot have cases with arguments
    case profile(Profile)
```

Or did I misunderstand something?

I think the question really boils down to: *"How do we use localizable strings?"*. I think we in most cases use them in certain **contexts**. Often these contexts are ViewControllers or parts of ViewControllers (using views). Where the syntax (that this issues proposes):

```swift
lazy var firstNameLabels: LabelsView = LabelsView(.firstName, value: self.user.firstName)
```

Is **vastly superior** to:

```swift
lazy var firstNameLabels: LabelsView = LabelsView(L10n.Sceen.Profile.Label.firstName, value: self.user.firstName)
```

Which just requires some `fileprivate` convenience initializer for the `LabelsView`, taking the nested enum `L13y.Screen.Profile.Label`:

```swift
extension LabelsView {
    // we can now pass the "leaf type" `L13y.Screen.Profile.Label`
    convenience init(_ key: L13y.Screen.Profile.Label, value: String) {
        self.init(key.translated, value: value)
    }
}
```

**Comment by Sajjon** [comment]
@djbe Hey David! Any update regarding my proposal? :) You do see the advantage? :)

**Comment by djbe** [comment]
Hey @Sajjon,

I was actually thinking about this concept this morning, and not only for (structured) strings, but also for assets as well. Now, your solution is essentially the old case-based templates. We got rid of them for the reasons mentioned above, and they don't solve issues in some cases. 

So the whole point of this is that we want places in the app, where we can provide a type to a function, and that function is then able to take some values out of it, because it knows that type has certain properties. For example, for assets, I have the following structure:
```swift
enum DarkTheme {
  static let background = ...
  static let header = ...
}
enum LightTheme {
  static let background = ...
  static let header = ...
}
```
Say I want to be able to tell a view to configure itself given a theme. To be able to guarantee that both the light and dark themes have the same properties/functions, I would have to use a `Theme` protocol:
```swift
protocol Theme {
  static var background: ... { get }
  static var header: ... { get }
}
```
Now you can actually easily conform all your themes to that theme protocol using extensions:
```swift
extension LightTheme: Theme {}
extension DarkTheme: Theme {}
```

The example above is for assets, but could just as easily be applied to strings. Now this isn't something that can be automatically generated by SwiftGen, but it should be possible with Sourcery (I think). I don't know if this concept would help you out?

**Comment by djbe** [comment]
While definitely an interesting feature, I think this is better achieved using protocols to enforce structure and available properties (as mentioned above). Should more people have interest in this, we can always reopen the discussion in the [SwiftGen](https://github.com/SwiftGen/SwiftGen) repository.
