### ISSUE TITLE
Swift 4 templates

### ISSUE THREAD

**Issue by djbe** [SwiftGen/templates#63]
As mentioned in https://github.com/SwiftGen/SwiftGen/issues/312 by @csnu17, there apparently are some issues with the current templates on swift 4.

We should fix these errors(*), and if possible, use new language features to simplify the templates where needed.

_(*) more accurately, create a new `swift4` template—based on the `swft3` templates but with fixes to make it compile to Swift 4— so that we'll keep both `swift3` and `swift4` templates for the users of SwiftGen to choose from_

**Comment by AliSoftware** [comment]
There's currently a note in the README mentioning that "we don't have Swift 4 templates yet but they are coming soon"; reminder that we should obviously not forget to remove that note once this issue is implemented.

**Comment by djbe** [comment]
@csnu17 SwiftGen 5 was released today. Could you provide some sample code where the current `swift 3` template fails when using swift 4 code? From cursory testing in playgrounds, everything seems to work for me.
