### ISSUE TITLE
Fonts: Only one 'register' called per font family

### ISSUE THREAD

**Issue by mortenbekditlevsen** [SwiftGen/templates#78]
I am not certain if it is possible to have an entire font family in the same file, but in case you have each font weight in a separate file (like RobotoSlab-Light.ttf, RobotoSlab-Bold.ttf, etc.) then only the first one will be registered - since the test for registering only queries to see if the font family is present.

For iOS/Swift 3 this can be fixed by changing the Font convenience initializer in the fonts/swift3.stencil to have the following check:

    if !UIFont.fontNames(forFamilyName: font.family).contains(font.name) {
      font.register()
    }

Do you agree that this is a sensible way to perform the check? If so, I can create a pull request with changes for all swift versions and both iOS/macOS.

**Comment by mortenbekditlevsen** [comment]
Haha, just saw that this exact change was committed 11 hours ago, so the issue is already resolved. Closing.

**Comment by AliSoftware** [comment]
Thanks for reporting the issue! 

Actually the problem was already reported and [the PR submitted and merged](https://github.com/SwiftGen/templates/pull/77) so should be included in the next release :wink:
